### ISSUE TITLE
Consider putting tally/1 into module Hangman

### ISSUE THREAD

**Issue by bobek** [pragdave/e4p-code#1]
Hi,

at the end of the chapter (checkpoint `050-start-hangman-complete`) you have suggested moving `make_move/2` directly under public API module `Hangman`. Following the same logic, I would suggest that `tally/1` should be also there. So the code would read

```elixir
defmodule Hangman do
  alias Hangman.Game

  defdelegate new_game(), to: Game

  def make_move(game, guess) do
    game = Game.make_move(game, guess)
    { game, tally(game)}
  end

  def tally(game) do
    %{
      game_state: game.game_state,
      turns_left: game.turns_left,
      letters:    game.letters |> reveal_guessed(game.used),
    }
  end

  ############################################################################

  defp reveal_guessed(letters, used) do
    letters |> Enum.map(fn letter -> reveal_letter(letter, MapSet.member?(used, letter)) end)
  end

  defp reveal_letter(letter, _in_word = true), do: letter
  defp reveal_letter(_letter, _not_in_word), do: "_"

end
```

I've put the `reveal_guessed` there as well as it seems as a transform function which is used to create a public API (sort of view functionality).

Honestly, I am not really sure if I like it :)

**Comment by pragdave** [comment]
So the idea is that the top level will be no actual code.

As we go on, you'll see that we cut this down again.
