### ISSUE TITLE
Supervisor code deprecated?

### ISSUE THREAD

**Issue by 9mm** [pragdave/e4p-code#3]
According to the docs it says this code is deprecated, but I'm still wrapping my head around the new actual code

https://hexdocs.pm/elixir/Supervisor.html

**Comment by MichelBartz** [comment]
Yes, though IEX was helpful in fixing that part of the code. 

You'll need to implement `child_spec` in `Dictionary.WordList`, IEX dumps an example that's almost correct as you need to ignore the `opts` argument and remove it from the list in the `:start` option. The start_link needs to change in `Dictionary.Application` as well, you need to remove the call to `worker()` and define the children list as such:

```
 children = [
      {Dictionary.WordList, []}
    ]
```
Not on my laptop will check the code later to confirm but IIRC that's all I changed to get it to compile.

**Comment by pragdave** [comment]
I think just adding

use GenServer

To WordList will do the trick.

**Comment by 9mm** [comment]
I made this issue before I saw the great video released after how to convert to DynamicSupervisor 👌🏼
