### ISSUE TITLE
Question about Genservers and Agents

### ISSUE THREAD

**Issue by ghost** [pragdave/e4p-code#7]
I understand why you used an Agent to handle state in the Dictionary application.

What I don't understand is why you chose to use Genserver to manage state in the Hangman application. Why didn't you use Agents if they can also get the job done?

**Comment by pragdave** [comment]
An Agent is intended to be nothing more that a state holder. One that agent
has more logic than one or maybe two accessors, then you're probably moving
into GenServer territory. Once there, you can integrate your code with all
the GenServer lifecycle management stuff.


Dave
